### ISSUE TITLE
Could you please upload datasets related to semantic_map, thank you very much

### ISSUE THREAD

**Issue by LXY572** [Oghma/sns-lstm#2]
I am watching your code on github, but I found that your code is missing the semantic_map part.
I am wondering if you could kindly upload the missing part. I promise they will be used only for research purposed.

**Comment by Oghma** [comment]
Here you can find the semantic maps: https://www.dropbox.com/sh/tk9lykwg6f5akpv/AADaV_lh7PmOiSGAMV-KSgMUa?dl=0
